version: "3.9"

services:
  user-management:
    build:
      context: ./../user-management
      dockerfile: Dockerfile
      target: development
    image: skn1942/shopc-usermanagement
    ports:
      - 9000:9000
    expose:
      - 9000
    # command: >
    #   sh -c "npx prisma generate && npm run start:dev"
    command: >
      sh -c "npx prisma migrate dev --name init && npm run start:dev"
    environment:
      - POSTGRES_DB=user-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=user-management-db
      - POSTGRES_PORT=5432
      - NATS_URL=nats://nats-server:4222
      - PORT=9000
    volumes:
      - ./../user-management:/usr/src/app
    depends_on:
      - nats-server

  user-management-db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=user-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - user-management-data:/var/lib/postgresql/data/
  # user-management-mongodb:
  #     image: mongo:latest
  #     ports:
  #       - 27017:27017
  #     environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: testPassword1234
  #     volumes:
  #     - user-management-data:data/db/

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./../gateway
      target: development
    image: skn1942/shopc-gateway
    ports:
      - 9001:9001
    expose:
      - 9001
    command: npm run start:dev
    volumes:
      - ./../gateway:/usr/src/app
    environment:
      - PORT=9001
      - USER_MANAGEMENT_HOST=user-management
      - USER_MANAGEMENT_PORT=9000
      # - RESTAURANT_HOST=restaurant
      # - RESTAURANT_PORT=9993
      # - CART_HOST=cart
      # - CART_PORT=9994
      # - ORDER_HOST=order
      # - ORDER_PORT=9995
    depends_on:
      - user-management

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    expose:
      - 4222
    command: -c nats-server.conf -DV

volumes:
  user-management-data:
