export enum UserMessagePatterns {
    USER_SIGN_UP = "USER_SIGN_UP",
    USER_LOGIN = "USER_LOGIN",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",
    USER_TOGGLE_ACTIVATION = "USER_TOGGLE_ACTIVATION",
    USER_VERIFY = "USER_VERIFY",
    USER_MAKE_ADMIN = "USER_MAKE_ADMIN",
    USER_REMOVE_ADMIN_ROLE = "USER_REMOVE_ADMIN_ROLE",
    USER_GET_BY_CRIDENTIAL = "USER_GET_BY_CRIDENTIAL"
}