name: tests-user-management

on: 
  pull_request:
    paths:
      - 'user-management/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run : cd user-management && yarn && yarn run test
